version: 0.2
phases:
  install: 
    runtime-versions:
      docker: 18
    commands: 
      - apt-get update -y
      - apt-get install -y jq
      - terraformImage="hashicorp/terraform:0.12.23"
      - docker pull $terraformImage
      - PROJ_NAME="$PROJETCT_NAME"
      - REPOSITORY_URI="$ECR_ADDRESS"
      - mkdir .aws && aws s3 cp s3://hackathon-fiap-1dvp-12345/instance-need/.aws/credentials .aws/ && aws s3 cp s3://hackathon-fiap-1dvp-12345/instance-need/.aws/config .aws/
      - mkdir .ssh && aws s3 cp s3://hackathon-fiap-1dvp-12345/instance-need/.ssh/fiap-lab.pem .ssh/ 
  pre_build:
    commands:
      - login=$(aws ecr get-login --region=us-east-1)
      - login=$(echo $login | sed 's/-e none/ /g' | tee)
      - echo $login | bash      
  build:
    commands:
      - dockerterraform="docker run --rm -w /app  -v $PWD:/app -v $PWD/.aws:/root/.aws -v $PWD/.ssh:/root/.ssh -e PROJ_NAME=$PROJ_NAME $terraformImage"
      - $dockerterraform init 
      - $dockerterraform workspace select $STAGE || $dockerterraform workspace new $STAGE
      - $dockerterraform destroy -var ECR_REGISTRY="${REPOSITORY_URI}" -auto-approve
      - $dockerterraform plan -var ECR_REGISTRY="${REPOSITORY_URI}" -out plan.out
      - $dockerterraform apply -var ECR_REGISTRY="${REPOSITORY_URI}" -auto-approve
      - elb=$($dockerterraform output elb_public)
      - echo $elb >> elb.txt
  post_build:
    commands:
      - echo "DONE!!!!"
    
artifacts:
  files: 
    - elb.txt
    - plan.out